---
name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@v5
        env:
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          VALIDATE_YAML: true
